apiVersion: v1
kind: Namespaces
metadata:
    name: dev
---
apiVersion: v1
kind: Namespaces
metadata::
    name: test    
---
apiVersion: v1
kind: Namespaces
metadata:
    name: staging   
---
apiVersion: v1
kind: Namespaces
metadata: 
   name: prod
